project:
  type: website
  output-dir: docs

website:
  title: "GSWEP4R Workshop"
  description: "`openstatsware` Workshop: Good Software Engineering Practice with R"
  site-url: https://openpharma.github.io/workshop-r-swe-mtl/
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: listing.qmd
        text: Slides
        icon: "file-earmark-slides"
  page-footer:
    center:
      - text: "About `openstatsware`"
        href: https://rconsortium.github.io/asa-biop-swe-wg/
      - text: "Source Code on GitHub"
        href: https://github.com/openpharma/workshop-r-swe-mtl

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: source
